datepicker/urls.py
from django.urls import path

from . import views
from .views import PromiseCreateView, detail_view, edit_view

app_name = 'datepicker'

urlpatterns = [
    # path('home/', views.home, name='home'),
    path('', PromiseCreateView.as_view()),  # class based view!
    # path('delete', views.delete, name='delete')
    path(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    # path(r'^edit/(?P<id>[0-9]+)/$', views.edit, name='edit'),
    # path(r'^detail_view/(?P<id>[0-9]+)/$', views.detail_view, name='detail_view')
    # path(r'^detail_view/(?P<id>[0-9]+)/$', detail_view, name='detail_view'),
    path('<id>', detail_view, name='detail_view'),
    path('<id>/edit', edit_view, name='edit_view')
]

howtousemongodbinDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# from .views import PromiseCreateView


urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='index'),
    # path('', PromiseCreateView.as_view() ),
    path('datepicker/', include('datepicker.urls')),
    path('todolist/', include('todoList.urls')),
    path('showbinancedata/', include('showbinancedata.urls')),
    path('admin/', admin.site.urls),
    # path(r'^detail_view/(?P<id>[0-9]+)/$', detail_view, name='detail_view'),
]

showbinancedata/urls.py
from django.urls import path
from . import views
from .views import getBinanceData

urlpatterns = [
    # path('', views.index, name='index'), # ignore after creating class based view
    path('', getBinanceData.as_view()),
]

todoList/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

datepicker/models.py
from django.db import models

# example for a class based view


class Promise(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    made_on = models.DateField()

    def __str__(self):
        return self.title

showbinancedata/models.py
from django.db import models

# example for a class based view


class binanceData(models.Model):
    COINPAIRS = [
        ('AVAX/EUR', 'AVAX/EUR'),
        ('BTC/EUR', 'BTC/EUR'),
        ('ETH/EUR', 'ETH/EUR'),
    ]
    ACCURACYS = [
        ('d', 'day'),
        ('h', 'hour'),
    ]

    coinpair = models.CharField(max_length=20, choices=COINPAIRS)
    accuracy = models.CharField(max_length=20, choices=ACCURACYS)
    start = models.DateField()
    end = models.DateField()

todoList/models.py
from django.db import models

# Create your models here.

datepicker/forms.py
from django import forms
from django.forms import ModelForm
from .models import Promise


class DateInput(forms.DateInput):
    input_type = 'date'


class PromiseForm(ModelForm):

    class Meta:
        model = Promise
        fields = ['title', 'description', 'made_on']
        widgets = {
            'made_on': DateInput(),
        }

showbinancedata/forms.py
from django import forms
from django.forms import ModelForm
from .models import binanceData


class DateInput(forms.DateInput):
    input_type = 'date'


class PromiseForm(ModelForm):
    class Meta:
        model = binanceData
        fields = ['coinpair', 'accuracy', 'start', 'end']
        widgets = {
            'start': DateInput(),
            'end': DateInput()
        }

datepicker/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Promise
from .forms import PromiseForm
from django.views.generic.edit import CreateView
from pymongo import MongoClient
from bson.objectid import ObjectId
from datetime import datetime

client = MongoClient('localhost', 27017)
db = client.django_db
entries = db.entries


class PromiseCreateView(CreateView):
    model = Promise
    form_class = PromiseForm
    # the cg part
    # template_name = '_promise_form.html'
    template_name = 'todoList/datepicker.html'
    def get(self, request):
        # return HttpResponse('result')
        form = self.form_class()
        all_entries = entries.find()

        return render(request, self.template_name, {'form': form, 'entries': all_entries})

    def post(self, request):
        form = self.form_class(request.POST)
        all_entries = entries.find()
        if form.is_valid():
            form.save()
            # print(type(form.cleaned_data['made_on']))
            print('form.cleaned_data: ', form.cleaned_data)
            print('form: ', form)
            # will not work, because mongodb don't accept datetime.date objects
            entries.insert_one({
                'title': form.cleaned_data['title'],
                'description': form.cleaned_data['description'],
                'made_on': datetime.combine(form.cleaned_data['made_on'], datetime.min.time())
            })
            form = self.form_class()

            return render(request, self.template_name, {'form': form, 'entries': all_entries, 'successful_submit': True})
        else:
            return render(request, self.template_name, {'form': form, 'entries': all_entries})

        # form = PromiseForm()
        # return HttpResponse('result')


def delete(request, id):
    # print(f'id: {id}, type(id): {type(id)}')
    # print(f'ObjectId(id): {ObjectId(id)}')
    entries.delete_one({"_id": ObjectId(id)})

    # return render(request, '_promise_form.html', {'form': form, 'entries': all_entries})
    return redirect('/datepicker')

'''
def edit(request, id=None):
    template_name = 'todoList/datepicker.html'
    form_class = PromiseForm
    if id:
        entry = get_object_or_404(Promise, pk=ObjectId(id))
        print('id in if: ', id)
    print(id)
'''

def detail_view(request, id):
    template_name = 'datepicker/detail_view.html'
    model = Promise
    form = PromiseForm
    entry = entries.find_one({"_id": ObjectId(id)})
    print(entry)

    return render(request, template_name, {'entry': entry})


def edit_view(request, id):
    template_name = 'datepicker/edit_view.html'
    entry = entries.find_one({"_id": ObjectId(id)})
    form = PromiseForm(request.POST or None)
    print('form: ', form.changed_data)

    if form.is_valid():
        form.save()
        entries.find_one_and_update({"_id": ObjectId(id)}, {"$set": {'title': form.cleaned_data['title'],
                                                                     'description': form.cleaned_data['description'],
                                                                     'made_on': datetime.combine(form.cleaned_data['made_on'], datetime.min.time()),
                                                                     'update': datetime.now()}}, upsert=False)
        # return HttpResponseRedirect("datepicker/")
        return redirect('/datepicker')

    return render(request, template_name, {'form': form, 'entry': entry})


# def home(response):
#     return render(response, "main/home.html", {})

howtousemongodbinDjango/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(response):
    # return HttpResponse("Hello world")
    return render(response, "todoList/home.html", {})

showbinancedata/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import binanceData
from .forms import PromiseForm

from django.http import HttpResponse


class getBinanceData(CreateView):
    model = binanceData
    form_class = PromiseForm
    template_name = 'todoList/showbinancedata.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})


# def index(response):
#     return render(response, "todoList/showbinancedata.html", {})

todoList/views.py
from django.shortcuts import render

from django.http import HttpResponse


# def index(request):
#     return HttpResponse("Todo List")

def index(response):
    return render(response, "todoList/todolist.html", {})

datepicker/templates/datepicker/detail_view.html
{% extends 'todoList/base.html' %}

{% block title %}
Datepicker - Detail view
{% endblock %}

{% block content %}
{% load tagger %}
<h1>Datepicker - Detail view</h1>
<p>{{ entry.title }}, {{ entry.description }}, {{ entry.made_on }}, {{ entry|underscoreTag:'_id' }}</p>
{% endblock %}

datepicker/templates/datepicker/edit_view.html
{% extends 'todoList/base.html' %}

{% block title %}
Update view
{% endblock %}

{% block content %}
<h3>Update view</h3>
<form action="" method="post" class="form-group">
    {% csrf_token %}
    <div class="input-group mb-3">
        {{ form.as_p }}
        <div class="input-group-prepend">
            <button type="submit", name="Update" class="btn btn-success">Update</button>
        </div>

    </div>
</form>
{% endblock %}

datepicker/templates/promise_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
    <!--<button type="submit", name="save">Create New</button>-->

</form>
<hr>
{% load tagger %}
{% for entry in entries %}

    <div class="entry">

        <p>{{ entry.title }}, {{ entry.description }}, {{ entry.made_on }}, {{ entry|underscoreTag:'_id' }}</p>
        <a class="btn btn-outline-danger" href="{% url 'datepicker:delete' id=entry|underscoreTag:'_id' %}">Delete</a>

    </div>
{% endfor %}

todoList/templates/todoList/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <style type="text/css">

        .main{
            margin-left:5px;
            padding: 0px 5px;
        }

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <title>{% block title %}CG's Website{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/home">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="/datepicker">Datepicker</a>
          <a class="nav-item nav-link" href="/todolist">Todo Lost</a>
          <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
      </div>
    </nav>

    <div id="content" name="content" class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">My Site</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

todoList/templates/todoList/datepicker.html
{% extends 'todoList/base.html' %}

{% block title %}
Datepicker
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Datepicker</h1>
<form action="" method="post">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
    {{ form|crispy }}
    <button type="submit", name="save">Create New</button>
</form>
{% load tagger %}
{% for entry in entries %}
<div class="input-group mb-3">
    <div class="input-group-prepend">
        <div class="input-group-text">
        <!--<p>{{ entry.title }}, {{ entry.description }}, {{ entry.made_on }}, {{ entry|underscoreTag:'_id' }}</p>-->
            {% if entry.update == None %}
                <article class="blog-post">
                    <h2 class="blog-post-title">{{ entry.title }}</h2>
                    <p class="blog-post-meta">Created on date, by author</p>
                    <p>{{ entry.description }}</p>
                    <hr>
                    <p>{{ entry.made_on }}</p>
                </article>
            {% else %}
                <article class="blog-post">
                    <h2 class="blog-post-title">{{ entry.title }}</h2>
                    <p class="blog-post-meta">Created on date, by author</p>
                    <p>{{ entry.description }}</p>
                    <hr>
                    <p>{{ entry.made_on }}</p>
                    <hr>
                    <p>edited on: {{ entry.update }}</p>
                </article>
            {% endif %}
            <a class="btn btn-outline-danger" href="{% url 'datepicker:edit_view' id=entry|underscoreTag:'_id' %}"><i class="bi bi-pencil"></i>Edit</a>
            <a class="btn btn-outline-danger" href="{% url 'datepicker:delete' id=entry|underscoreTag:'_id' %}"><i class="bi bi-trash"></i>Delete</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

todoList/templates/todoList/home.html
{% extends 'todoList/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
{% endblock %}

todoList/templates/todoList/showbinancedata.html
{% extends 'todoList/base.html' %}

{% block title %}
ShowBinanceData
{% endblock %}

{% block content %}
<h1>Show Binance Data</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
</form>
{% endblock %}

todoList/templates/todoList/todolist.html
{% extends 'todoList/base.html' %}

{% block title %}
TodoList
{% endblock %}

{% block content %}
<h1>Todo List</h1>
{% endblock %}